Resources:
  webserver:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1d
      ImageId: ami-43a15f3e
      InstanceType: t2.micro
      KeyName: crack
      SecurityGroupIds:
        - sg-49f0e600
      Tags:
        - Key: name
          Value: load-balancer
