---
- name: install tools
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: ensure db listening on all ports
  lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: ^bind-address
      line: 'bind-address = {{ ansible_eth0.ipv4.address }}'
  notify: restart mysql

- name: ensure mysql service started
  service:
    name: mysql
    state: started
    enabled: true

- name: create db
  mysql_db:
    name: '{{ db_name }}'
    state: present
    config_file: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: create user
  mysql_user:
    name: '{{ db_user_name }}'
    password: '{{ db_user_pass }}'
    state: present
    priv: '{{ db_name}}.*:ALL'
    host: '{{ db_host }}'
