---
  - hosts: dbserver
    become: true
    tasks:
      - name: install mysql-server
        apt: name=mysql-server state=present update_cache=yes

      - name: ensure mysql service started
        service:
          name: mysql
          state: started
          enabled: yes

      - name: ensure db is listening on all ports
        lineinfile:
          path: /etc/mysql/my.cnf
          regexp: ^bind-address
          line: 'bind-address = 0.0.0.0'
        notify: restart mysql

    handlers:
      - name: restart mysql
        service:
          name: mysql
          state: restarted

