---
  # Bringing stack down
  - hosts: loadbalancer
    become: true
    tasks:
      - name: stop loadbalancers
        service:
          name: nginx
          state: stopped

      - wait_for:
          port: 80
          state: drained

  - hosts: webserver
    become: true
    tasks:
      - name: stopping apache2
        service:
          name: apache2
          state: stopped

      - wait_for:
          port: 80
          state: stopped

  # Restarting Database server
  - hosts: dbserver
    become: true
    tasks:
      - name: restarting mysql-server
        service:
          name: mysqld
          state: restarted

      - wait_for:
          port: 3306
          state: started

  # Bringing stack up
  - hosts: webserver
    become: true
    tasks:
      - name: starting apache2
        service:
          name: apache2
          state: started

      - wait_for:
          port: 80

  - hosts: loadbalancer
    become: true
    tasks:
      - name: starting loadbalancers
        service:
          name: nginx
          state: started

      - wait_for:
          port: 80
