---
  - hosts: webserver
    become: true
    tasks:
      - name: install web components
        yum:
          name: "{{item}}"
          state: present
          update_cache: yes
        with_items:
          - httpd
          - mod_wsgi
          - python-pip
          - python-virtualenv

      - name: ensure httpd started
        service:
          name: httpd
          state: started
          enabled: yes

      - name: ensure mod_wsgi enabled
        apache2_module:
          name: wsgi
          state: present
        notify: restart httpd

      - name: copy app demo files
        copy:
          src: demo/app/
          dest: /var/www/demo
          mode: 0755
        notify: restart httpd

      - name: copy apache virtual host config
        copy:
          src: demo/demo.conf
          dest: /etc/httpd/sites-available
          mode: 0755
        notify: restart httpd

    handlers:
      - name: restart httpd
        service:
          name: httpd
          state: restarted
