---
  - hosts: webserver
    become: true
    tasks:
      - name: "install web components"
        apt: name="{{item}}" state=present update_cache=yes
        with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

      - name: ensure apache2 is enabled
        service:
          name: apache2
          state: started
          enabled: yes

      - name: ensure wsgi module is enabled
        apache2_module:
          state: present
          name: wsgi
        notify: restart apache2

      - name: copy demo app to webserver
        copy:
          src: /etc/ansible/demo/app/
          dest: /var/www/demo
          mode: 0755
        notify: restart apache2

      - name: copy apache virtual hosst config
        copy:
          src: /etc/ansible/demo/demo.conf
          dest: /etc/apache2/sites-available
          mode: 0755
        notify: restart apache2

    handlers:
      - name: restart apache2
        service:
          name: apache2
          state: restarted
