---
  - hosts: webserver
    become: true
    tasks:
      - name: install web components
        yum:
          name: "{{item}}"
          state: present
          update_cache: yes
        with_items:
          - httpd
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

