---
  - hosts: webserver
    become: true
    pre_tasks:
      - name: install python2
        raw: sudo apt-get -y install python-simplejson

    tasks:
      - name: install web components
        apt:
          name: "{{item}}"
          state: latest
          update_cache: yes
          with_items:
            - apache2
            - libapache2-mod-wsgi
            - python-pip
            - python-virtualenv
